//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poje_SQL_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMIN
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
    }
}
